### PR TITLE
Split Russia by administrative districts

### PR DESCRIPTION
**Pull request by andreynovikov**
I've checked all files for syntax and for visual conformity to map outlines, but when I tried to generate maps some of them failed with weird errors. May be it's because my computer is too feeble.

### CODE REVIEW

**Comment by ludwigb** [comment]
I will try over the weekend, thanks
Am 04.02.2015 23:13 schrieb "Andrey Novikov" notifications@github.com:

**Comment by ludwigb** [comment]
I have merged your pull request in, thank you, and I have now restarted the map creation process. This will take some time (we are talking days here) until it reaches Russia. I will check the output and result later and see if anything goes wrong.

**Comment by andreynovikov** [comment]
Cool!

**Comment by applantation** [comment]
Will take a bit more time to arrive at Russia....

**Comment by ludwigb** [comment]
Looks like the new Russia maps are all there now:
http://download.mapsforge.org/maps/europe/russia/

Our whole Russia map has failed again with a OOM error, I have given it
another 2GB of memory (now 14GB) to see what happens when we run it again.

Andrey, can you check the maps?

**Comment by andreynovikov** [comment]
Personally I do not see any reason to keep the whole Russia on server.

I'll check them, thanks.

**Comment by andreynovikov** [comment]
There are three problems with generated maps:
1. All regions that are outside Europe are empty because they are clipped by Europe bounding box. May be we should introduce Eurasia or simply move Russia one level up.
2. All empty tiles are covered with "natural->nosea" area. When I created my test maps empty tiles were empty (and transparent, as I use mapsforge transparency flag). Now transparency is broken.
3. Chukotsky region map is huge. It's something wrong with polygon or with bounding box calculation. Still downloading it so can not say more precisely.

**Comment by devemux86** [comment]
> All empty tiles are covered with "natural->nosea" area. When I created my test maps empty tiles were empty (and transparent, as I use mapsforge transparency flag). Now transparency is broken.

Maybe related to [#579](https://github.com/mapsforge/mapsforge/issues/579)

**Comment by ludwigb** [comment]
The issue is probably, as Andrey noticed, that anything below Europe is cut
out of the Europe polygon, so moving Russia up one level (meaning its main
outline will be cut from the world, so the Asian parts will be included)
should solve the problem.

I could do that maybe today or tomorrow.

Ludwig

**Comment by applantation** [comment]
I have moved Russia up to the top level and restarted the process. Since
with that the russia polygon will be cut out of the planet, the empty area
problem should be solved.

I put Russia at the top so that Russia will be made first, so we will see a
bit earlier what has been fixed and what not.
1. Chukotsky region map is huge. It's something wrong with polygon or with
   > bounding box calculation. Still downloading it so can not say more
   > precisely.

Andrey, that will be up to you to fix, I would not even be able to place
this on a map.

Ludwig

**Comment by andreynovikov** [comment]
I've looked at Chukotsky region. As I expected the problem is that it is intersected by 180 parallel. This leads to the wrong bounding box: minLat = 61.66, minLon = -180, maxLat = 72.79, maxLon = 180 (all the globe around). Can you advice how to fix it properly?

**Comment by applantation** [comment]
That is probably difficult, I guess the best way would be to split it along
the date line and make two parts of it.

I guess lots of mapsforge stuff will not actually work correctly across the
date line either.

(The usual trick employed, I guess, is to continue counting upwards as one
moves east, so 180->181 etc, but I think our LatLong classes and other
stuff will just blow up with it.)

Ludwig

**Comment by andreynovikov** [comment]
Ok, I'll split it. Meanwhile, can you remove Chukotsky region from the map generation process for the time being?

**Comment by andreynovikov** [comment]
I think you have to move polygon files as well, because now it's not generated at all.

**Comment by ludwigb** [comment]
Thanks for spotting, I have done this and restarted the generation
process...

**Comment by andreynovikov** [comment]
Don't you have to move `russia.poly` as well?

**Comment by ludwigb** [comment]
Gnats, probably true, will fix soon.
 Am 12.03.2015 06:56 schrieb "Andrey Novikov" notifications@github.com:

**Comment by applantation** [comment]
Changed that and restarted the process.

**Comment by andreynovikov** [comment]
Something went totally wrong now... All maps that have generated so far today are 3-4 times smaller then they were in previous generation. I've tried to open some - they miss data randomly. Some roads, some forests, some water. Looks very strange.

**Comment by applantation** [comment]
My suspicion is that somehow the restarted process overran with the old
one, I had thought I had killed the old one off, but maybe not.
For a moment I thought it was a partially downloaded planet file, but at
22GB it seemed the right size.

I have cleaned everything up and restarted the process again, wait and see
if that was the problem.

**Comment by andreynovikov** [comment]
No. That didn't help. Maps are still ~3 times smaller than month ago and missing random data. May be it's something wrong with mapwriter? Have you changed it during this month? May be you can test it on your home map?

I will illustrate. This is the map that was generated on February 19:
screenshot_2015-03-15-10-57-17

And this is the map generated on March 14:
screenshot_2015-03-15-10-55-48

**Comment by applantation** [comment]
Another try:

I have now changed the configuration on the server so that the Russia
subdistricts will be built from the planet file, rather than an intermedia
Russia subset. (This is in case that somehow the Russia polygon causes
problems: the size of the Russia intermediate pbf file was 1.2GB, as
compared to about 1.7GB combined size of Russia Europe/Asia on geofabrik).

There was no change in the writer file, but I have now updated it to the
latest 0.5.1-rc4 writer. The last one was the official 0.5.0 writer.

I have also cleaned out all intermediate data, so it should not be able to
pick up any stale files.

Ludwig

**Comment by devemux86** [comment]
The issue with empty maps appears to be general.
e.g. I just downloaded berlin.map and it's quite empty.

**Comment by applantation** [comment]
Same problem everywhere, I planet file that was short. The current one
looks the right size.

I guess the problem was somehow triggered by restarting the process, I
assume that, even though I tried to kill off the previous process it
continued generating maps when the planet file was being redownloaded.

**Comment by andreynovikov** [comment]
Confirm that everything (so far) is ok now.

**Comment by andreynovikov** [comment]
There is no issue tracker in this repository so I would as here: what's your policy on map language? Currently Russian maps are half in Russian half in English depending on availability of name:en key. Shouldn't we set map language for country maps to national language?

**Comment by devemux86** [comment]
The common used key and default is the [Key:name](http://wiki.openstreetmap.org/wiki/Key:name).
The content actually depends on which language users have used when they filled it.
Also I don't think it's for sure that `name:<lg>` is always filled.

**Comment by ludwigb** [comment]
> Confirm that everything (so far) is ok now.
> 
> Thanks for checking, looks like starting everything from fresh solved the
> problem.

**Comment by applantation** [comment]
On 17 March 2015 at 13:57, Emux notifications@github.com wrote:

> The common used key and default is the Key:name
> http://wiki.openstreetmap.org/wiki/Key:name.
> The content actually depends on which language users have used when they
> filled it.
> Also I don't think it's for sure that name:<lg> is always filled.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mapsforge/mapsforge-mapcreator/pull/1#issuecomment-82478704
> .
> 
> At the end of the day the mapsforge download server is just a service. It
> is impossible to satisfy every demand that is being put on it and we do no
> really have the capacity to process all languages.

I think the bigger issue is the problem that mapsforge does not support
multiple languages at the same time.

Ludwig

**Comment by devemux86** [comment]
> There is no issue tracker in this repository

Indeed maybe we should have issues list for map creator too.
But for questions we should discuss them in the [forum](https://groups.google.com/forum/#!forum/mapsforge-dev).

> I think the bigger issue is the problem that mapsforge does not support multiple languages at the same time.

+1
We have already talked about that in the mailing list.
There are tricks that can be used but at the end a full solution should be implemented.

**Comment by ludwigb** [comment]
I have turned the issues on on the mapsforge/mapcreator project.

Feel free to raise issues, including the ones that have already been
reported on this list.

Ludwig

**Pull request merged**
