### PR TITLE
Add French departements. Rename Centre.

### PR DESCRIPTION
**Pull request by peter17**
Polygons were generated with polygons.openstreetmap.fr

The start positions are the coordinates of the préfectures (main
administrative cities of the départements). Coordinates are from
Wikidata.

Centre was renamed to "Centre-Val de Loire" by the law in 2015:
http://www.legifrance.gouv.fr/jopdf/common/jo_pdf.jsp?numJO=0&dateJO=20150117&numTexte=1&pageDebut=00777&pageFin=00783

### CODE REVIEW

**Comment by ludwigb** [comment]
Thanks for the suggestions. 

In principle I have nothing against the inclusion of more areas, but I think this gets to France specific and we do not have the capacity to produce maps for all areas on this planet, so I am not really planning to integrate this patch into our server builds.

However, this is useful if someone wanted to run their own server for France. Can I suggest that you package this up as a separate config-france.xml file, so other people could download and run it who are particularly interested in France?

**Comment by devemux86** [comment]
I agree with Ludwig, the map generation can get out of hand if we aren't careful about our hardware limits.
We certainly need to include many missing countries and probably split the big ones into major regions without exaggerating that.

His suggestion about separate xml is valid and would help everyone interested.

**Comment by peter17** [comment]
I can produce a separate xml, although I think having smaller regions would be more manageable, in particular in mobile apps.

I don't have the resources to run my own server now...

**Comment by applantation** [comment]
If you produce a separate xml file, then I can just add this to a run on
our server to see how it performs.

Ludwig

**Comment by devemux86** [comment]
One thing to consider is that if the over splitting starts to become common for many countries then the world build process cycle will be even slower to refresh.

**Comment by devemux86** [comment]
Thanks, I squashed and merged manually the PR with additional fixes, so I'm closing this.

As mentioned [here](https://groups.google.com/d/msg/mapsforge-dev/AK3yjjd8E6s/a6Ct5V7b-i8J), please keep the PR commits squashed (depending the case), in order to avoid the clutter in repository and have only the finally changed files together.

One way is described here:
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Pull request closed without merging**
