### PR TITLE
Add Georgia

### PR DESCRIPTION
**Pull request by andreynovikov**
A map for Georgia (country)

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks, could you provide separate PRs, as they involve different issues?

**Comment by andreynovikov** [comment]
Removed the second one for the time being

**Comment by ludwigb** [comment]
The problem is that the original data comes in a different directory, just too troublesome to fix. Sorry.

**Comment by andreynovikov** [comment]
@ludwigb Can you explain? I've tested it on my computer and it successfully generated the map.

**Comment by devemux86** [comment]
> The problem is that the original data comes in a different directory

Ludwig refers here about the OSM [structure](http://download.geofabrik.de/europe/georgia.html) and how each region comes from its parent continent.

**Comment by andreynovikov** [comment]
@devemux86 Yes, I've checked this before creating pull request. Your Europe polygon splits Georgia in a half, but Asia polygon fully covers it. That's why I've put it in Asia section. There are two opinions on where to put Georgia geographically, but putting it into Asia is more common. Moreover Georgia, Armenia, and Azerbaijan are considered as one region, and you have put Azerbaijan in Asia so it's reasonable to put Georgia in Asia too.

Another option is to extend Europe polygon up to Caspian sea or make it more complex to cover full Georgia like it is done in http://download.geofabrik.de/europe.html

If you wish I will do it.

**Comment by applantation** [comment]
Please do not make Europe even bigger (nothing political, it is really a
speed/space problem).

If it is covered by Asia we can do it.

**Comment by devemux86** [comment]
@ludwigb why not using in map-creator the ready and well tested Geofabrik polygons for all the continents / countries?

That way there is a common and already working structure which can enrich our regions to all supported.

**Pull request closed without merging**
